### ISSUE TITLE
Problems to download the dataset

### ISSUE THREAD

**Issue by naanadr** [zhhoper/DPR#4]
Hi, your work is amazing and thanks to share with us.

But I have a problem to download the dataset, Google say "download quota exceeded". 
Do you know about that? Do you have other methods to download the dataset?

**Comment by zhhoper** [comment]
Hi, I think you can wait for some time and try again. It seems google has a download quota which will be reset every 24 hours. Let me know if you still have that issue.

**Comment by naanadr** [comment]
Thanks, now I can download.
