### ISSUE TITLE
How To Generate Custom 'rotate_light_00.txt' File

### ISSUE THREAD

**Issue by JeremyOgo** [zhhoper/DPR#5]
I'm trying to understand how the values in these files were generated.

Am I right to assume that the 9 values in each rotate_light_xx.txt file are the first nine spherical harmonic coefficients? 

Any advice on how someone could define new ones based on a new direction the light is coming from?

**Comment by JeremyOgo** [comment]
OK I believe I have figured out a workable solution. Below is a function that will generate the lighting .txt file base on the input theta and phi angles, as described by the scipy.special.sph_harm documentation found here:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.sph_harm.html

```
def createSH(theta_deg, phi_deg):
        
    from scipy import special
    import numpy as np
    
    theta = theta_deg*np.pi/180
    phi = phi_deg*np.pi/180
    
    a = np.real(special.sph_harm(0,0,theta,phi))
    b = np.real(special.sph_harm(-1,1,theta,phi))
    c = np.real(special.sph_harm(0,1,theta,phi))
    d = np.real(special.sph_harm(1,1,theta,phi))
    e = np.real(special.sph_harm(-2,2,theta,phi))
    f = np.real(special.sph_harm(-1,2,theta,phi))
    g = np.real(special.sph_harm(0,2,theta,phi))
    h = np.real(special.sph_harm(1,2,theta,phi))
    i = np.real(special.sph_harm(2,2,theta,phi))
    
    text_file = open("OutputLighting.txt", "w")
    
    text_file.write(str(a)+"\n")
    text_file.write(str(b)+"\n")
    text_file.write(str(c)+"\n")
    text_file.write(str(d)+"\n")
    text_file.write(str(e)+"\n")
    text_file.write(str(f)+"\n")
    text_file.write(str(g)+"\n")
    text_file.write(str(h)+"\n")
    text_file.write(str(i)+"\n")
    
    text_file.close()
```

I think there is a normalization or scaling ambiguity, causing the resulting lighting to be too dark, but this can be adjusted by changing the multiplication factor in this line:

```
sh = sh * 0.7
```

in the testNetwork_demo_xxxx.py script

**Comment by zhhoper** [comment]
I think the best practice to generate custom's lighting is to create an environment map and get SH from that. For that part, you can use shtools, it has a function to convert an environment map to SH. The way you use is to get the value of the basis SH function along a particular direction. To be specific, you can get the nine coefficients from any of the lighting files provided, multiply them with the a to i created by your function, then you get the lighting intensity of the environment along direction (theta, phi). To understand SH lighting, you can read this paper http://www.weizmann.ac.il/math/ronen/sites/math.ronen/files/uploads/basri_jacobs_-_lambertian_reflectance_and_linear_subspaces.pdf
